release-date = "2020-11-27"

[[entries]]
id = "1457094f-b0ee-4c4a-b517-a41e8e535014"
type = "feature"
description = "packages now inherit the monorepos license if it is unset (using PackageModel.get_license())"
author = "@NiklasRosenstein"

[[entries]]
id = "552e756c-aeca-46cd-b20c-765ff2465e45"
type = "feature"
description = "If a package inherits the monoreop license, the LICENSE file will not be replicated in the package directory but instead be copied from the monorepo (using `_tempcopy()` in `setup.py`)"
author = "@NiklasRosenstein"

[[entries]]
id = "98731f72-57be-44bc-8956-5041f713e588"
type = "feature"
description = "`shut {mono,pkg} update` commands now produce a LICENSE.txt file if a license template exists for the specified license (currently only `MIT`)"
author = "@NiklasRosenstein"

[[entries]]
id = "1bbd20ac-2e8f-4bf1-a410-e2cee3b449c2"
type = "feature"
description = "packages now inherit the monorepo `author` and `url`, and `version` if `release.single_version == True`"
author = "@NiklasRosenstein"

[[entries]]
id = "69522f75-4205-4930-8b91-4456350bbff0"
type = "feature"
description = "add \"shut pkg format\" command"
author = "@NiklasRosenstein"

[[entries]]
id = "19c8a510-a343-472a-bb2b-9a6fd321af3a"
type = "feature"
description = "package `author` and `url` are now inherited from the monorepo"
author = "@NiklasRosenstein"
