release-date = "2021-08-09"

[[entries]]
id = "45104b69-935c-4b9e-9a71-145d295cf2db"
type = "feature"
description = "add `shut mono|pkg status --json --include-config` options"
author = "@NiklasRosenstein"
