release-date = "2021-09-04"

[[entries]]
id = "822ae588-1f29-4d49-81ef-fa6888e3dec7"
type = "fix"
description = "min `click` version must be `7.1` for `no_args_is_help` option, also allow `8.x`"
author = "@NiklasRosenstein"
