release-date = "2020-08-29"

[[entries]]
id = "e0ee08af-ff2e-4aee-b795-e6c37e4c16de"
type = "improvement"
description = "update Changelog typing for databind"
author = "@NiklasRosenstein"

[[entries]]
id = "f73bf327-b2a1-4e6c-9eef-b438599e0aa8"
type = "improvement"
description = "update paths printed in `shut ... bump` when changelog is released"
author = "@NiklasRosenstein"
