release-date = "2022-02-25"

[[entries]]
id = "b4fcc652-2f8a-4419-a879-b693711da1dc"
type = "fix"
description = "fix consistent sorting of packages ordered topologically by interdependencies"
author = "@NiklasRosenstein"

[[entries]]
id = "7dff63e3-0c6c-42bd-a3c6-06b8853e07bc"
type = "feature"
description = "recognize `tool.poetry.packages` option in `DefaultProjectHandler.get_packages()`"
author = "@NiklasRosenstein"
