release-date = "2023-09-08"

[[entries]]
id = "bd6c84f9-120b-4262-ad66-949e7529d11f"
type = "fix"
description = "Use new Version for poetry-core and lock minor version"
author = "@alexespencer"
pr = "https://github.com/NiklasRosenstein/slap/pull/96"
issues = [
    "https://github.com/NiklasRosenstein/slap/issues/95",
]
