release-date = "2023-08-10"

[[entries]]
id = "232946ab-fb46-416e-a798-fa7c6a54484f"
type = "feature"
description = "Add fish to supported shells for shimming"
author = "@jonhoo"
pr = "https://github.com/NiklasRosenstein/slap/pull/92"
