release-date = "2023-12-14"

[[entries]]
id = "dcd60d11-3358-422d-a86a-474795372cd8"
type = "improvement"
description = "allow passing `none` or `null` for the `slap init --license` parameter"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/103"

[[entries]]
id = "af82da0c-1c32-45e0-a28d-534a17c63ea6"
type = "feature"
description = "Add `slap venv --no-upgrade-pip` option and automatically upgrade Pip after creating a virtual environment if the option is not specified."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/103"
issues = [
    "https://github.com/NiklasRosenstein/slap/issues/102",
]

[[entries]]
id = "d8af87d8-191f-40e8-8099-e5a5618cf230"
type = "improvement"
description = "remove dependency on `pkg_resources` directly in the module, although a transitive dependency (`nr.util.plugin`) still uses it"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/104"
issues = [
    "https://github.com/NiklasRosenstein/slap/issues/98",
]

[[entries]]
id = "c5d94767-38b7-4b01-8669-c5aaf027d0ab"
type = "fix"
description = "Fixed a bug in `slap release` where an unreleased changelog in the project root was not renamed and updated in a mono repository"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/105"
