release-date = "2024-09-02"

[[entries]]
id = "28678c39-12c1-4472-80d5-2bb608fed9da"
type = "improvement"
description = "Improve error message when version number is not consistent across files"
author = "niklas.rosenstein@helsing.ai"
