release-date = "2022-05-23"

[[entries]]
id = "a3bfa069-d920-4269-92af-1a7c74f74a56"
type = "fix"
description = "Add missing black options to init template"
author = "@NiklasRosenstein"

[[entries]]
id = "bfa2dff6-fb5f-4c23-ba26-1cd4c657b708"
type = "improvement"
description = "Init template now uses dmypy by default"
author = "@NiklasRosenstein"

[[entries]]
id = "4f109020-213c-4c33-adfd-4c12fc9dbc18"
type = "improvement"
description = "Set python_version = 3.6 in Init template"
author = "@NiklasRosenstein"

[[entries]]
id = "c1192d47-238f-4564-a020-ff7a7f6bde1d"
type = "fix"
description = "`slap install` no longer calls Pip without dependenciesto install, instead it prints this info and exits successfully"
author = "@NiklasRosenstein"
