release-date = "2022-04-28"

[[entries]]
id = "7fd54dfa-8411-4d1c-a24b-61b5ebd93a19"
type = "fix"
description = "Automatic detection of packages now ignores subdirectories that have a `pyproject.toml` file"
author = "@NiklasRosenstein"
