[[entries]]
id = "429d780d-af40-4606-8a2d-a97ba0cc4362"
type = "feature"
description = "the `--only` option to `slap install` can now receive multiple values delimited by commas, the `slap test` command now also takes an `--only` option."
author = "@NiklasRosenstein"
