[[entries]]
id = "cb9ff9fc-b96b-4996-9a02-ff9f1ca004ca"
type = "feature"
description = "add `slam changelog <directory>` argument, defaults to the same as `--name`"
author = "@NiklasRosenstein"

[[entries]]
id = "8e765aad-d150-4baa-b942-80161afbdcc3"
type = "improvement"
description = "`slam init` now understands dots as namespace packages"
author = "@NiklasRosenstein"

[[entries]]
id = "b7dad5e7-e1d9-4977-aa0f-08156cf0fbf8"
type = "improvement"
description = "`slam init` package name written into `pyproject.toml` keeps dots"
author = "@NiklasRosenstein"

[[entries]]
id = "06af48b7-a6c2-48af-957b-3078cd489720"
type = "feature"
description = "add `slam run` command"
author = "@NiklasRosenstein"
