[[entries]]
id = "3f6cc68c-9ae1-4814-a9d9-a5799af9a300"
type = "improvement"
description = "upgrade to using `databind` 2.x"
author = "@NiklasRosenstein"

[[entries]]
id = "f0bcce7c-345c-42eb-851f-7c4b8f44a546"
type = "breaking change"
description = "Rename Slam to Clap"
author = "@NiklasRosenstein"

[[entries]]
id = "52a29516-ef0a-4b53-bd22-1ca5d36b3d9d"
type = "improvement"
description = "Split default project handler into separate implementations for Poetry, Flit and Setuptools and properly support Setuptools now (reading `setup.cfg`)"
author = "@NiklasRosenstein"

[[entries]]
id = "71d0c4b2-e7c4-4474-b688-20bc9a06a624"
type = "feature"
description = "add `-b,--build-directory` option to `clap publish` command"
author = "@NiklasRosenstein"

[[entries]]
id = "fb745286-30a0-40cf-9a2f-b40970e48ffa"
type = "feature"
description = "add `slam.check.check()` decorator and `slam.check.get_checks()` function to make implementing check plugins more convenient"
author = "@NiklasRosenstein"
