[[entries]]
id = "d795c58c-f99f-42cb-aeb7-a0e70fd24d97"
type = "fix"
description = "Fix creation of activate scripts when creating virtual environments with `venv` by passing the correct flag `--upgrade-deps` instead of `--upgrade`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/python-slap/slap-cli/issues/135",
]
