[[entries]]
id = "ce84fd8b-2093-46c2-aff0-ff937101f809"
type = "breaking change"
description = "Reimplement command to update PRs in added changelog entries and rename it to `slap changelog diff pr update`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/75"

[[entries]]
id = "8628d6e9-3906-4810-aa5a-279dcd830f6a"
type = "improvement"
description = "Update `GithubActionsChangelogUpdateAutomationPlugin.get_pr()` to return the full PR URL instead of just the number."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/75"
