[[entries]]
id = "04ac6c34-39c7-43ec-8b88-e9c76b902ff1"
type = "fix"
description = "Fix `slam install` command accessing the wrong option name for `--no-venv-check` causing an error when `--link` was used"
author = "@NiklasRosenstein"
