[[entries]]
id = "77d1e90e-4d46-40e6-9cce-a28f0cd3a88f"
type = "fix"
description = "fix error message on missing `py.typed` file"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/slap/issues/62",
]
