[[entries]]
id = "a638368d-2f7d-492a-a11c-f3de05a32f19"
type = "improvement"
description = "`slam changelog update-pr` no longer overwrites existing PR references in entries unless the new `--overwrite` option is passed"
author = "@NiklasRosenstein"
