[[entries]]
id = "e9114573-01d9-41d3-b701-39a18c057559"
type = "refactor"
description = "add `Repository` and `RepositoryHandlerPlugin` which gets to decide which projects are loaded, remove most of the related members from the `Application` class"
author = "@NiklasRosenstein"

[[entries]]
id = "895eae85-f569-43a8-bc94-34b4462e3dd1"
type = "improvement"
description = "morph `VcsHost` into `RepositoryHost` class"
author = "NiklasRosenstein"

[[entries]]
id = "93d5a5e9-b9a3-4e7c-ae63-689e4a534876"
type = "fix"
description = "fix possible `AssertionError` in `Application._get_main_project()` that can occur if Slam is invoked in a directory that does not contain a `pyproject.toml` nor `slam.toml` file."
author = "@NiklasRosenstein"

[[entries]]
id = "336311d4-26f3-406f-91bd-4e764a90738e"
type = "improvement"
description = "`slam changelog format` in the Terminal now colorizes inline code (indicated by backticks)"
author = "@NiklasRosenstein"
