[[entries]]
id = "4d25d208-2f53-46ee-a99d-27d71e731b2c"
type = "improvement"
description = "`test` command no info-logs the command being run"
author = "@NiklasRosenstein"

[[entries]]
id = "00410e5a-28d2-422f-bc93-d4c0695907a4"
type = "feature"
description = "add `slam test -l,--list` option"
author = "@NiklasRosenstein"

[[entries]]
id = "4d2ff9b3-dbde-42d1-8e4d-5902e01cf35e"
type = "improvement"
description = "`slam init -t poetry` now creates a test file"
author = "@NiklasRosenstein"

[[entries]]
id = "7c61697e-dc56-40ba-886c-26b544774fae"
type = "fix"
description = "Fix `slam init` to create a `test/test_import.py` instead of `test/test.py`"
author = "@NiklasRosenstein"

[[entries]]
id = "9ded719d-4ae4-41b1-82f9-f0640e1c13b0"
type = "fix"
description = "Fix `slam install` command to forward to the `--no-venv-check` option to the `slam link` command"
author = "@NiklasRosenstein"

[[entries]]
id = "2260124e-ce9f-46a2-9401-4fbf5fe198d0"
type = "fix"
description = "Fix `slam changelog convert` to use the proper default author"
author = "@NiklasRosenstein"
