[[entries]]
id = "1326c953-8cd4-486d-8a5e-a78f7e3d045c"
type = "fix"
description = "Dependency with extras are now written correctly into `pyprojec.toml` for Poetry projects"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/84"
issues = [
    "https://github.com/NiklasRosenstein/slap/issues/81",
]

[[entries]]
id = "be756b0c-cfbd-40c2-8312-09f5d17889fa"
type = "feature"
description = "The `slap run` command can now run the commands defined in every project of a monorepository (if set), only if the monorepository does not define the command itself (in `slap.toml`)."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/85"
issues = [
    "https://github.com/NiklasRosenstein/slap/issues/82",
]
