[[entries]]
id = "69eb006e-0206-4aea-87fa-69bf2000a3f3"
type = "improvement"
description = "Get rid of deprecated `nr.util` dependency by placing all the required bits of code into Slap itself"
author = "@NiklasRosenstein"
