[[entries]]
id = "5b9f7374-2d99-4a46-b359-e876e34e6beb"
type = "breaking change"
description = "Slap now tries to find the repository root even if the current working directory is in a sub-directory of a project in that mono repository. By default, projects in a mono repository will all share the same Virtual environment. This can be disabled by setting the `[tool.slap].shared_venv` setting in `pyproject.toml` to `false`."
author = "@NiklasRosenstein"

[[entries]]
id = "b66b2aa6-2abe-4dbe-a189-4a70e8fa2352"
type = "improvement"
description = "`slap install` from a project inside a mono repository will only install that specific project and, if any, its dependencies among the projects in the same monorepository."
author = "@NiklasRosenstein"

[[entries]]
id = "13afd41a-e4db-40b5-bc6a-1fa25fc3425b"
type = "improvement"
description = "Ensure that `slap check`, `slap publish`, `slap report`, `slap run` and `slap test` only run in the context of the main project when in a subdirectory mapping to a Project instead of the entire repository."
author = "@NiklasRosenstein"
