[[entries]]
id = "86cb742b-9867-4903-bbcd-4574d42482ba"
type = "improvement"
description = "use more concrete branch name for checkout in `github-actions` plugin to work around issues if the branch name is the same as a top level folder in the repository"
author = "@NiklasRosenstein"
