[[entries]]
id = "ce84fd8b-2093-46c2-aff0-ff937101f809"
type = "breaking change"
description = "Reimplement command to update PRs in added changelog entries and rename it to `slap changelog diff pr update`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/75"

[[entries]]
id = "8628d6e9-3906-4810-aa5a-279dcd830f6a"
type = "improvement"
description = "Update `GithubActionsChangelogUpdateAutomationPlugin.get_pr()` to return the full PR URL instead of just the number."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/75"

[[entries]]
id = "5cbf8941-8b3d-40d0-85d9-51cc25f983da"
type = "breaking change"
description = "Rename `ChangelogUpdateAutomationPlugin` to `GitRepositoryHostPlugin`, add `GitRepositoryHostPlugin.all()` and `~.get()`, rename plugin entrypoint from `slap.plugins.changelog_update_automation` to `slap.plugins.git_repository_host`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/75"

[[entries]]
id = "43f8c133-975a-4b99-8531-53dd4404ea29"
type = "feature"
description = "add `slap changelog diff assert-added`"
author = "@NiklasRosenstein"
