[[entries]]
id = "b04948f0-abde-4327-a090-7e8ee30180c6"
type = "improvement"
description = "Enhance docs and output of `slap venv` command"
author = "@NiklasRosenstein"

[[entries]]
id = "07c4879b-bbce-4a60-b9fb-7389ad1d3ef5"
type = "improvement"
description = "The `slap venv` command can now be used with `-a,--activate` and without a `name` argument to activate the previously activated environment or the only one that is available in the context (local vs. global)."
author = "@NiklasRosenstein"

[[entries]]
id = "8d85b2a5-5fdc-49b2-916a-905348e3978f"
type = "improvement"
description = "Improve `ChangelogReleasePlugin` to write \"releasing changelog\" line only once"
author = "@NiklasRosenstein"

[[entries]]
id = "790ff132-9782-43fa-99f1-f2866f01cf17"
type = "improvement"
description = "Improve changelog checks plugin to catch more types of errors to return in the check details"
author = "@NiklasRosenstein"

[[entries]]
id = "acad8c34-9c3b-4ed7-a198-3ba0f2ef9b4e"
type = "improvement"
description = "improve output produces by `slap venv -a`, `slap publish` and `slap release`"
author = "@NiklasRosenstein"
