[[entries]]
id = "f065877b-eecb-4577-90fb-d18c1fb381af"
type = "breaking change"
description = "Drop support for installing into Python 3.6 virtual environments"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/118"

[[entries]]
id = "f98854c7-5ec9-4c17-a98c-78809e81bae9"
type = "improvement"
description = "Upgrade UV to ^0.2.0"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/slap/pull/141"
