[[entries]]
id = "6ac10f2d-25b1-4193-8007-c9c695fe54ab"
type = "feature"
description = "add `-p,--path` option to `slap venv` command, note that `-p` was repurposed from `--python` and the option no longer has a short form"
author = "@NiklasRosenstein"

[[entries]]
id = "efa1e01f-ea4d-4e0c-b7b3-05c60617c629"
type = "improvement"
description = "`slap test` and `slap run` commands now activate the active virtual environment if any before running the commands"
author = "@NiklasRosenstein"

[[entries]]
id = "b3c70f28-839c-4da1-88e0-39194777ffc1"
type = "feature"
description = "Add `-s,--set` option to `slap venv`"
author = "@NiklasRosenstein"

[[entries]]
id = "dfdc1851-cc98-449c-86f1-c8ccf8884397"
type = "improvement"
description = "The `slap run` command can now run arbitrary commands, but falls back to the ones aliased on the configuration on a match."
author = "@NiklasRosenstein"
