steps:
- shut changelog -a --markdown > docs/docs/changelog.md
- echo "============="
- echo mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml
- mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml
