name: 'slap - Update changelogs'
description: 'Updates changelogs managed by Slap to inject the pull request reference.'
inputs:
  version:
    description: The version of Slap to install
    required: true
    default: '*'
runs:
  using: "composite"
  steps:

    - uses: NiklasRosenstein/slap@gha/install/v1
      with: { version: "${{ inputs.version }}" }

    - name: Update changelogs
      shell: bash
      run: slap -vv changelog update-pr --use github-actions
