name: 'slap - Update changelogs'
description: 'Updates changelogs managed by Slap to inject the pull request reference.'
inputs:
  version:
    description: The version of Slap to install. Defaults to `>=1.7.0`.
    required: false
    default: '>=1.7.0'
  ref:
    description: A Git ref to install Slap from. If this is specified, the version input is ignored.
    required: false
    default: ''
  pr-id:
    description: When running in a `pull_request_target` event, the Pull Request ID cannot be derived from and
      environment variable. It must be passed here.
    required: false
  github_token:
    description: Pass along the Github token.
    required: true
    default: '${{ github.token }}'
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4

    - run: git fetch
      shell: bash

    - uses: NiklasRosenstein/slap@gha/install/v1
      with: { version: "${{ inputs.version }}", ref: "${{ inputs.ref }}" }

    - name: Update changelogs
      shell: bash
      run: slap changelog diff pr update --use github-actions -vv
      env: { GITHUB_TOKEN: '${{ inputs.github_token }}', GITHUB_PR_ID: '${{ inputs.pr-id }}' }
