name: 'Install Slap'
description: 'Install Slap into your Action environment using Python 3.10 and Pipx.'
inputs:
  version:
    description: The version of Slap to install
    required: false
    default: '*'
  ref:
    description: A Git ref to install Slap from. If this is specified, the version input is ignored.
    required: false
    default: ''
runs:
  using: "composite"
  steps:

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with: { python-version: "3.10" }

    - name: Install Slap
      shell: bash
      run: |
        VERSION='${{ inputs.version }}'
        REF='${{ inputs.ref }}'

        if [ ! -z "$REF" ]; then
          install_arg="git+https://github.com/NiklasRosenstein/slap.git@$REF"
        elif [ "$VERSION" == '*' ]; then
          install_arg="slap-cli"
        elif [[ $VERSION =~ ^[0-9] ]]; then
          install_arg="slap-cli==$VERSION"
        else
          install_arg="slap-cli$VERSION"
        fi

        echo "Installing: $install_arg"
        pip install pipx -q && pipx install "$install_arg"
