name: 'slap - Update changelogs'
description: 'Updates changelogs managed by Slap to inject the pull request reference.'
inputs:
  version:
    description: The version of Slap to install. Defaults to `>=1.7.0`.
    required: true
    default: '>=1.7.0'
runs:
  using: "composite"
  steps:

    - run: git fetch
    - run: git checkout $GITHUB_HEAD_REF
      if: github.head_ref != ''

    - uses: NiklasRosenstein/slap@gha/install/v1
      with: { version: "${{ inputs.version }}" }

    - name: Update changelogs
      run: slap changelog diff pr update --use github-actions -vv
