name: 'Setup Slam'
description: 'Sets up the Slam command-line utility.'
inputs:
  version:
    description: The Slam version
    required: true
    default: '*'
runs:
  using: "composite"
  steps:

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with: { python-version: "3.10" }

    - name: Install Slam
      run: pip install pipx -q && pipx install 'slam-cli==${{ inputs.version }}'
