name: 'slap - Update changelogs'
description: 'Updates changelogs managed by Slap to inject the pull request reference.'
inputs:
  version:
    description: The version of Slap to install. Defaults to `>=1.7.0`.
    required: true
    default: '>=1.7.0'
  ref:
    description: A Git ref to install Slap from. If this is specified, the version input is ignored.
    required: false
    default: ''
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v2

    - run: git fetch
      shell: bash

    - run: env
      shell: bash

    - run: git checkout $GITHUB_HEAD_REF
      shell: bash
      if: github.head_ref != ''

    - uses: NiklasRosenstein/slap@gha/install/v2
      with: { version: "${{ inputs.version }}", ref: "${{ inputs.ref }}" }

    - name: Update changelogs
      shell: bash
      run: slap changelog diff pr update --use github-actions -vv
