[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "clap-cli"
version = "1.2.4"
description = "Slam is a command-line utility for developing Python applications."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
packages = [{ include="clap", from="src" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Programming Language :: Python :: 3.10",
]

[tool.poetry.urls]
Documentation = "https://niklasrosenstein.github.io/clap/"
Homepage = "https://github.com/NiklasRosenstein/clap"
Repository = "https://github.com/NiklasRosenstein/clap.git"

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.10.0"
cleo = ">=1.0.0a4"
"databind" = "^2.0.0a1"
flit = "^3.6.0"
"nr.util" = ">=0.8.4,<1.0.0"
poetry-core = "^1.1.0a6"
ptyprocess = "^0.7.0"
pygments = "^2.11.2"
PyYAML = ">=4.0"
requests = "^2.27.1"
tomli = "^2.0.0"
twine = "^3.7.0"

[tool.poetry.dev-dependencies]
types-beautifulsoup4 = "^4.10.0"
types-requests = "^2.27.7"
types-PyYAML = "^6.0.3"
types-pygments = "^2.9.16"
mypy = "^0.931"

[tool.poetry.extras]
docs = ["mkdocs", "mkdocs-material", "novella==0.1.15", "pydoc-markdown==4.6.0"]

[tool.poetry.scripts]
slam = "clap.__main__:main"  # For backwards compatibility
clap = "clap.__main__:main"

[tool.poetry.plugins."clap.plugins.application"]
changelog = "clap.ext.application.changelog:ChangelogCommandPlugin"
check = "clap.ext.application.check:CheckCommandPlugin"
info = "clap.ext.application.info:InfoCommandPlugin"
init = "clap.ext.application.init:InitCommandPlugin"
install = "clap.ext.application.install:InstallCommandPlugin"
link = "clap.ext.application.link:LinkCommandPlugin"
publish = "clap.ext.application.publish:PublishCommandPlugin"
release = "clap.ext.application.release:ReleaseCommandPlugin"
run = "clap.ext.application.run:RunCommandPlugin"
test = "clap.ext.application.test:TestCommandPlugin"
venv = "clap.ext.application.venv:VenvPlugin"

[tool.poetry.plugins."clap.plugins.changelog_update_automation"]
github-actions = "clap.ext.changelog_update_automation.github_actions:GithubActionsChangelogUpdateAutomationPlugin"

[tool.poetry.plugins."clap.plugins.check"]
changelog = "clap.ext.checks.changelog:ChangelogValidationCheckPlugin"
general = "clap.ext.checks.general:GeneralChecksPlugin"
poetry = "clap.ext.checks.poetry:PoetryChecksPlugin"
release = "clap.ext.checks.release:ReleaseChecksPlugin"

[tool.poetry.plugins."clap.plugins.release"]
changelog_release = "clap.ext.release.changelog:ChangelogReleasePlugin"
interdependencies = "clap.ext.release.interdependencies:InterdependenciesReleasePlugin"
source_code_version = "clap.ext.release.source_code_version:SourceCodeVersionReferencesPlugin"

[tool.poetry.plugins."clap.plugins.version_incrementing_rule"]
major = "clap.ext.version_incrementing_rule:major"
premajor = "clap.ext.version_incrementing_rule:premajor"
minor = "clap.ext.version_incrementing_rule:minor"
preminor = "clap.ext.version_incrementing_rule:preminor"
patch = "clap.ext.version_incrementing_rule:patch"
prepatch = "clap.ext.version_incrementing_rule:prepatch"
prerelease = "clap.ext.version_incrementing_rule:prerelease"

[tool.poetry.plugins."clap.plugins.project"]
flit = "clap.ext.project_handlers.flit:FlitProjectHandler"
poetry = "clap.ext.project_handlers.poetry:PoetryProjectHandler"
setuptools = "clap.ext.project_handlers.setuptools:SetuptoolsProjectHandler"

[tool.poetry.plugins."clap.plugins.repository"]
default = "clap.ext.repository_handlers.default:DefaultRepositoryHandler"

[tool.poetry.plugins."clap.plugins.repository_host"]
github = "clap.ext.repository_hosts.github:GithubRepositoryHost"

[tool.clap]
typed = true

[tool.clap.test]
mypy = "mypy src --namespace-packages"
check = "clap check"

[tool.clap.run]
"docs:dev" = "cd docs && novella --serve"

[tool.mypy]
pretty = true
warn_redundant_casts = true
#warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
show_error_context = true
show_error_codes = true
