[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "slam-cli"
version = "1.0.0a3"
description = "Slam is a command-line utility for developing Python applications."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
packages = [{ include="slam", from="src" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Programming Language :: Python :: 3.10",
]

  [tool.poetry.urls]
  Documentation = "https://niklasrosenstein.github.io/slam/"
  Homepage = "https://github.com/NiklasRosenstein/slam"
  Repository = "https://github.com/NiklasRosenstein/slam.git"

  [tool.poetry.dependencies]
  python = "^3.10"
  beautifulsoup4 = "^4.10.0"
  "databind.core" = "^1.4.0"
  "databind.json" = "^1.4.0"
  flit = "^3.6.0"
  "nr.util" = "^0.5.0"
  cleo = ">=1.0.0a4"
  poetry-core = "^1.1.0a6"
  pygments = "^2.11.2"
  PyYAML = "^6.0"
  requests = "^2.27.1"
  tomli = "^2.0.0"
  ptyprocess = "^0.7.0"

  [tool.poetry.dev-dependencies]
  types-beautifulsoup4 = "^4.10.0"
  types-requests = "^2.27.7"
  types-PyYAML = "^6.0.3"
  types-pygments = "^2.9.16"
  mypy = "^0.931"

  [tool.poetry.scripts]
  slam = "slam.__main__:main"

  [tool.poetry.plugins."slam.plugins.application"]
  changelog = "slam.ext.application.changelog:ChangelogCommandPlugin"
  check = "slam.ext.application.check:CheckCommandPlugin"
  link = "slam.ext.application.link:LinkCommandPlugin"
  release = "slam.ext.application.release:ReleaseCommandPlugin"
  test = "slam.ext.application.test:TestCommandPlugin"
  # poetry = "slam.poetry.plugin:PoetryPlugin"
  # github = "slam.changelog.ext.github:GithubApplicationPlugin"

  [tool.poetry.plugins."slam.plugins.check"]
  changelog = "slam.ext.checks.changelog:ChangelogValidationCheckPlugin"
  general = "slam.ext.checks.general:GeneralChecksPlugin"
  poetry = "slam.ext.checks.poetry:PoetryChecksPlugin"
  release = "slam.ext.checks.release:ReleaseChecksPlugin"
  # [tool.poetry.plugins."slam.plugins.check"]
  # github = "slam.changelog.ext.github:GithubRemoteProvider"

  [tool.poetry.plugins."slam.plugins.release"]
  changelog_release = "slam.ext.release.changelog:ChangelogReleasePlugin"
  source_code_version = "slam.ext.release.source_code_version:SourceCodeVersionReferencesPlugin"

  [tool.poetry.plugins."slam.plugins.version_incrementing_rule"]
  major = "slam.ext.version_incrementing_rule:major"
  premajor = "slam.ext.version_incrementing_rule:premajor"
  minor = "slam.ext.version_incrementing_rule:minor"
  preminor = "slam.ext.version_incrementing_rule:preminor"
  patch = "slam.ext.version_incrementing_rule:patch"
  prepatch = "slam.ext.version_incrementing_rule:prepatch"
  prerelease = "slam.ext.version_incrementing_rule:prerelease"

  [tool.poetry.plugins."slam.plugins.vcs_host_detector"]
  github = "slam.ext.vcs_hosts.github:GithubVcsHostDetector"

  [tool.poetry.plugins."slam.plugins.vcs_host_provider"]
  github = "slam.ext.vcs_hosts.github:GithubVcsHostProvider"

[tool.slam]
typed = true

  [tool.slam.test]
  mypy = "mypy src --namespace-packages"
  check = "slam check"

[tool.mypy]
pretty = true
warn_redundant_casts = true
#warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
show_error_context = true
show_error_codes = true
