site_name: Slap
repo_url: https://github.com/NiklasRosenstein/slap
repo_name: NiklasRosenstein/slap
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: teal

exclude_docs: |
  !.github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            separate_signature: true
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - getting-started.md
  - configuration.md
  - glossary.md
  - Commands:
    - slap add: commands/add.md
    - slap changelog: commands/changelog.md
    - slap check: commands/check.md
    - slap info: commands/info.md
    - slap init: commands/init.md
    - slap install: commands/install.md
    - slap link: commands/link.md
    - slap publish: commands/publish.md
    - slap release: commands/release.md
    - slap report: commands/report.md
    - slap run: commands/run.md
    - slap test: commands/test.md
    - slap venv: commands/venv.md
  - Guides:
    - guides/github.md
  - API:
    - api/plugins.md
    - api/documentation.md
  - changelog.md
