nav:
  - index.md
  - usage-examples.md
  - configuration.md
  - glossary.md
  - Commands:
    - slap add: commands/add.md
    - slap changelog: commands/changelog.md
    - slap check: commands/check.md
    - slap info: commands/info.md
    - slap init: commands/init.md
    - slap install: commands/install.md
    - slap link: commands/link.md
    - slap publish: commands/publish.md
    - slap release: commands/release.md
    - slap run: commands/run.md
    - slap test: commands/test.md
    - slap venv: commands/venv.md
  - Guides:
    - guides/github.md
    - guides/publishing.md
  - Plugins:
    - plugins/project-handlers.md
  - API:
    - api/plugins.md
    - api/documentation.md
  - Other:
    - changelog.md
