docs_dir: src
site_name: Slam
repo_url: https://github.com/NiklasRosenstein/slam

theme: material
markdown_extensions:
- pymdownx.betterem
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed: { alternate_style: true }
- pymdownx.tasklist: { custom_checkbox: true }
- pymdownx.tilde
