name: "Python Package"

on:
  push:
    branches: [ "develop" , "rename-to-clap" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install poetry==1.2.0a2 .
    - name: Install with poetry
      run: pip install . && clap install --no-venv-check
    - name: Test
      run: clap info && clap test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout branch if PR
      if: github.event_name == 'pull_request'
      run: git checkout -b $GITHUB_HEAD_REF
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with: { python-version: "3.10" }
    - name: Install dependencies
      run: python -m pip install pipx -q && pipx install . && clap install --only-extras docs --no-venv-check -vv
    - name: Build documentation
      run: cd docs && novella --base-url clap/
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_site

  docs-publish:
    needs: [ test, docs ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs/_site
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: rosensteinniklas@gmail.com
        build_dir: docs/_site
