name: "Python Package"

on:
  push:
    branches: [ "develop" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: pip install . && slap install --no-venv-check
    - run: slap info && slap test

  test-pep508:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: python src/slap/python/pep508.py

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 0 }
    - run: git checkout -b $GITHUB_HEAD_REF
      if: github.event_name == 'pull_request'
    - uses: actions/setup-python@v2
      with: { python-version: "3.10" }
    - run: python -m pip install pipx -q && pipx install . && slap install --only-extras docs --no-venv-check -vv
    - run: slap run docs:build
    - uses: actions/upload-artifact@v2
      with: { name: docs, path: docs/_site }

  docs-publish:
    needs: [ test, docs ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with: { name: docs, path: docs/_site }
    - uses: Cecilapp/GitHub-Pages-deploy@v3
      env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
      with: { email: rosensteinniklas@gmail.com, build_dir: docs/_site }
