name: "Python Package"

on:
  push:
    branches: [ "revamp" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "revamp" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install poetry==1.2.0a2 .
    - name: Install with poetry
      run: poetry install
    - name: Test
      run: poetry run slam test

  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: "3.9"
  #   - name: Install mkdocs
  #     run: pip install mkdocs
  #   - name: Build docs
  #     run: mkdocs build -d $PWD/html/ -f docs/mkdocs.yml -s
  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: docs
  #       path: html/

  # docs-publish:
  #   needs: [ test, docs ]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: docs
  #       path: html/
  #   - name: Deploy to GitHub Pages
  #     uses: Cecilapp/GitHub-Pages-deploy@v3
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       email: rosensteinniklas@gmail.com
  #       build_dir: html
