name: "Python Package"

on:
  push:
    branches: [ "develop" , "docs" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install poetry==1.2.0a2 .
    - name: Install with poetry
      run: pip install . && slam install --no-venv-check
    - name: Test
      run: slam test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with: { python-version: "3.10" }
    - name: Install dependencies
      run: python -m pip install slam-cli==1.0.0a15 && python -m venv .venv && source .venv/bin/activate && slam install
    - name: Run tests
      run: source .venv/bin/activate && slam test
    - name: Build documentation
      run: source .venv/bin/activate && cd docs && novella
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_site

  docs-publish:
    needs: [ test, docs ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs/_site
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: rosensteinniklas@gmail.com
        build_dir: docs/_site
